language: node_js

node_js:
  - '4.8'
  - '6.12'

cache:
  directories:
    - node_modules

services: mongodb

notifications:
  email:
    - jeremie.drouet@gmail.com

before_script:
  - npm install
  - npm run build

script:
  - npm test

after_script:
  - cat coverage/lcov.info | ./node_modules/codecov.io/bin/codecov.io.js
